Use exit codes

diff --git a/simplify-mtr.yml b/simplify-mtr.yml
--- a/simplify-mtr.yml
+++ b/simplify-mtr.yml
@@ -113,6 +113,7 @@ jobs:
         echo `cat $REPRO_DIR/simplification_cmd` "--output=\"$SEARCH_PATTERN\"" > $REPRO_DIR/simplification_cmd
       fi
       . $REPRO_DIR/simplification_cmd
+      res=$?
       cp suite/bug/repro.test $(Build.ArtifactStagingDirectory)/first_test.test
       tar zcf repro.output.tar.gz repro.output var/log/mysqld.1.err
       mv repro.output.tar.gz $(Build.ArtifactStagingDirectory)/
@@ -126,8 +127,15 @@ jobs:
       echo "We tried to reproduce the failure happened in $TRIGGERING_ARTIFACT_ID of pipeline $TRIGGERING_PIPELINE_ID, build $TRIGGERING_BUILD_ID)"
       echo "on the server " `head -n 2 $REPRO_DIR/repro.info`
       echo "while searching for pattern $SEARCH_PATTERN"
+      echo ""
+      echo "RESULT: $res"
       echo "#######################################################################"
       echo ""
+      if [ "$res" == "1" ] ; then
+        echo "##vso[task.complete result=Failed]Could not reproduce the failure"
+      elif [ "$res" == "2" ] ; then
+        echo "##vso[task.complete result=SucceededWithIssues]The process ended due to approaching timeout"
+      fi
     name: simplify
     displayName: 'Prepare and run simplification'
 
